name: app-typescript-openapi-plugin
description: Plugin que aplica o conceito de contract first a partir de um contrato OpenAPI e gera todo o código fonte e infraestrutura necessários em CDK.
types:
  - app
inputs:
  - label: Defines the name of api, that may be used to link the generated source files and code references.
    type: text
    name: api_name
    default: api-name
    required: true
  - label: Defines the location path of the OpenAPI specification file, by default it is spec-file-name.
    type: text
    name: spec_file_name
    default: spec-file-name
    required: false
  - label: Defines the location path of the OpenAPI lambda generated files, by default it is src.
    type: text
    name: source_dir
    default: src
    required: false
  - label: Most IDM providers expose a JWKS_URI with their public keys to verify JWT token signatures. You need to use this input to inform JWKS_URI to be used to get the public keys.
    type: text
    name: jwks_uri
    required: false
  - label: If the contract to be worked with this plugin is already exposed on an API Gateway, this field should be informed with the entrypoint by each environment, dev, qa, prod, and so on, if not informed, an API Gateway CDK Implementation will be generated.
    type: bool
    name: virtualize_gateway
    default: true
    required: false
  - label: If the contract to be worked with this plugin is already exposed on an API Gateway, this field should be informed with the entrypoint by each environment, dev, qa, prod, and so on, if not informed, an API Gateway CDK Implementation will be generated.
    type: multiselect
    name: gateway_entry_points
    items:
      - item1
      - item2
    required: false

displayName: OpenAPI + API Gateway Plugin

category: backend

compatibility:
  - OpenAPI 3.0
  - NodeJS 14.x

about: about.md

usage: usage.md

useCase: useCase.md

implementation: implementation.md

technologies: [ "Typescript", "OpenAPI", "API Gateway" ]